name: Scrape latest data

on:
  push:
    branches:
      - main  # Change this to your main branch name
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write  # Allows pushing to the repository

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: "Check out this repo"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scrapers
        working-directory: .
        run: |
          python scrapers.py

      - name: "Commit and push if changes exist"
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u +"%Y-%m-%d %H:%M:%S")
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
